### ISSUE TITLE
Update quicklinks

### ISSUE THREAD

**Issue by e-aakash** [DevCom-IITB/instiapp-angular#78]
- Add SSO and services like MS Teams and GSuite
- Remove GPO
- CMS has to be removed

**Comment by pulsejet** [comment]
In the long run we might want to store the quick links in the database. Your call @e-aakash

**Comment by e-aakash** [comment]
Closed by https://github.com/wncc/instiapp-angular/pull/79

Enhancement to keep quick links in the database can be opened as a separate issue.
