### ISSUE TITLE
Highlight search string in blog's search results

### ISSUE THREAD

**Issue by jaindhairyahere** [DevCom-IITB/instiapp-angular#89]
The search bar in the blog is essentially a very useful feature. However, if I want to find the posts where my Name is mentioned, it gets very irritating. 

Current Version:- Returns the search results, but doesn't highlight the relevant lines in the post. So, if there are many lines of a list of students in a post, then it falls on the user to look for the searched name in all the returned posts.

Expected:- Return the search results, and highlight the relevant lines in the post, so that it becomes easier to find things without having to look into them. If possible, give an option to condense other data and just show the relevant parts of the post (Will add it as a new issue later).

**Comment by Krishna-Baldwa** [comment]
Implemented already
